blank_issues_enabled: true
contact_links:
  - name: Questions & Community Support
    url: https://github.com/MT-Syntax/makefile/discussions/new?category=q-a
    about: Please ask and answer questions about the Makefile syntax here.
